/**
 * This file include all kinds of data structure to describe the FEM problem
 * including mesh, elements, step, nlsolver, output, bcs
*/
#pragma once
enum MeshFileFormat{
    STRUCTURE,/**< structure mesh data generated by thus program*/
    MSH2,/**< GMSH mesh file of version 2.0 (.msh)*/
    MSH4,/**< GMSH mesh file of version 4.0 (.msh)*/
};
